apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mall-admin-client.configmapName" . }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}