apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mall-service.secretName" . }}
  namespace: {{.Values.namespace}}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}