---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mall-service.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "mall-service.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  selector:
    {{- include "mall-service.selectorLabels" . | nindent 4 }}
    app: {{.Values.app}}
  ports:
  - name: {{.Values.service.name}}
    port: {{.Values.service.port}}
    targetPort: {{.Values.deploy.containerPort}}
